name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge --project ./ --domain parcial-electiva2e.surge.sh
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
